# Generated by Django 3.0.6 on 2020-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='faq_title',
            field=models.CharField(default='FAQ', max_length=100),
        ),
    ]
