# Generated by Django 3.0.6 on 2020-07-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_about_faq_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
    ]
